### ISSUE TITLE
As as developer, I want to link the NISV RDF schema to the GTAA thesaurus

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#11]
- [x] decide how to model the GTAA concepts and their relationship to their schema ('as') so that it is clear for  each property and class in the RDF schema how it is related to the GTAA, and we can later use this information in reasoning and linking (e.g. finding the most frequently occurring persons in the archive)
- [ ] create a new version of the RDF schema that uses the GTAA

**Comment by mwigham** [comment]
do we create an RDFS version of the GTAA, with schemes as classes and concept as instances, and then use the schema classes as ranges (also has the advantage that we could use the ‘is a’ relationship to help search for values of a certain type, e.g. all people related to a programme: <programmeId> ?property ?value . ?value is a gtaa:Person)? Or another way? E.g. to create superclasses in the schema and do a relationship with the scheme URI?

**Comment by jblom** [comment]
@wmelder @mwigham also added this to the backlog, but to the bottom for now (not vital for v4, but nice to start working on whenever possible).

**Comment by mwigham** [comment]
@wmelder Do we still want to do this? Our current thinking is more to keep the schema separate from the details of how data is entered at Sound and Vision, and the GTAA schemes are quite a specific link to the implementation.

**Comment by jblom** [comment]
@mwigham @wmelder A nice solution is to create a separate graph just for linking the two. This way you can flexibily include/exclude this linking graph (& the GTAA graph) from your queries.

So this story could be about creating a linking graph.

What do you guys think?

**Comment by mwigham** [comment]
That would be a good solution, then we can use the knowledge without setting it in stone in the schema itself.

**Comment by wmelder** [comment]
I may be missing it, but I think in the comments in the schema we already provide the link between the catalog data and the GTAA. Since the iMMix data don't have URI's, but do have have the prefLabels from the conceptScheme they're from, we can modify the data, so the blank nodes ID's are replaced with the correct GTAA URI. The process doing that is depending on some scripting logic, I think. But maybe I am missing something here and we can have reasoning work for us? How would we have to model the matching logic in the triple store? That would be an interesting question I cannot answer yet.

**Comment by jblom** [comment]
@mwigham @wmelder let's organisse a pow-wow to work this one out on the white board soon :p

**Comment by wmelder** [comment]
think we have tackled this... closing it..
