### ISSUE TITLE
As a developer, I need to test the RDF generated by our initial OAI2LOD solution

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#18]
- [x] Install OAI2LOD locally on mwigham's machine
- [x] Review the RDF generated by the [OAI2LOD](https://github.com/beeldengeluid/beng-lod-server/issues/3) for a number of example archive objects
- [x] Make sure we have rdf Properties or Classes for all necessary elements from the bg namespace.
- [x] make sure the transformations from XML2RDF are correct and complete.
- [x] Discuss the differences between this RDF and the initial RDF schema and determine how to modify the schema and/or the OAI2LOD
- [x] Either carry out the modifications or create new issues if necessary

**Comment by mwigham** [comment]
Errors: isPartOf is incorrectly being modelled as a class instead of a property

**Comment by jblom** [comment]
@mwigham could you explain a bit more what you intend for this story?

**Comment by mwigham** [comment]
@jblom  This is the next step in developing the schema, testing generating data with the schema to see if it produces RDF that properly describes the concepts.

**Comment by mwigham** [comment]
@jblom can you test this please?  

- [ ] Make a selection of series, seasons, programmes and segment IDs
- [ ] Enter these in the [lod server](http://data.rdlabs.beeldengeluid.nl/) and in the Elastic Search cluster, and compare the metadata in the generated RDF to that in the ES cluster
- [ ] For major issues (e.g. server crashes, item not found, metadata value is incorrect) put this issue back into To Do
- [ ] Report minor issues (e.g. fields that belong together are linked directly to the programme instead of being grouped in a class such as Executive) in [this issue](url)

**Comment by jblom** [comment]
Some initial remarks when comparing program 128480:
- **depreactedKeyword** & **keywords** are merged into **schema:keyword**. Seems fine, but curious to hear the reason for this choice.
- **datestamp** (from ES) is not in the schema (but rightfully so I guess, since it's an importer date?)
- **bg:contest.bg:colour** is mapped to (predicate) **hasContext** pointing to a blank node of the **class Context** with the property **schema:colour**. It seems weird that the **class Context** has a property colour... Are there any other occurances of Context?
- **bg:qualification** (ES) is removed from the schema, instead only its child **bg:source** is mapped to **schema:source**
- **bg:broadcaster** seems like a good candidate for a GTAA concept, now it's a literal
- **bg:availablecollections** (in ES) is flattened to **schema:collection**. Sure this is not losing information?
- **bg:creator** is mapped to a bn with class Creator. I guess later on a GTAA link can be added to this class?

**Comment by jblom** [comment]
Remark when comparing season 67000 (part of program 128480):
- **genres** and **museum-genres** are merged into **schema:genre**. Is there a good reason for this? For now this solution makes it impossible to distinguish the two in the LD

**Comment by jblom** [comment]
Remark when comparing program 5356704:
- the LD version has a **schema:qualification** (with an empty string) while this information is not in the ES data
- **bg:transcripts** (in ES) are as expected not in the LD version

Remark when comparing season 439304 (part of said program):
- I don't see a **schema:isPartOfSeries** (pointing to series 379721)
- the program (5356704) does show a **schema:isPartOfSeason** as expected

**Comment by jblom** [comment]
@mwigham please judge yourself if this issue needs to be put in TODO. To me it seems things are mostly as expected. The only thing that could be a problem is the missing isPartOfSeason (see previous comment)

**Comment by mwigham** [comment]
@jblom @wmelder  Thanks for testing, Jaap. I think we should close this issue. I will copy Jaap's test findings to #22 and we can decide there which ones block further experimentation and so need to be solved now, and which we will pick up when we change the mapping for DAAN.

**Comment by mwigham** [comment]
@jblom, by the way, Context does indeed possess a property about colour, along with other things such as award and occasion.  It is a bit of an odd class - perhaps a good example of something we can improve on later (if DAAN hasn't already tackled it).

**Comment by jblom** [comment]
@mwigham @wmelder ok cool, closing this one then
