### ISSUE TITLE
As a LD user, I need the catalogue data labels to be matched with the GTAA concept labels, so that records with the same literal for a controlled field share the same GTAA concept URI.

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/beng-lod-server#42]
@jblom commented on [Thu Jun 27 2019](https://github.com/beeldengeluid/rd_infra_service/issues/8)

When we got the GTAA as a named graph, this can be used to improve the NISV catalogue data. This means that fields containing strings will be rewritten to skos concepts. To be able to do that we need to research the possibilities:

- [x] to combine two or more graphs, 
- [x] to match NISV literals to SKOS prefLabels (XL LiteralForm not necessary),
- [x] unfortunately, all literals need to be expanded with the lang tag. otherwise only FILTER queries are possible, which are notoriously slow for SPARQL engines

** Acceptance criteria **
- [x] Structered solution that does this given a (sub-)catalog, GTAA conceptScheme and rdfs class to be reconciled. 
- [ ] Code review

**Comment by wmelder** [comment]
This has been done, at least for the concepts from the 'GTAA/Onderwerpen', which is not so large.
The SPARQL request works (also delete triples that aren't needed), so we need to proceed with the other parts: Genre, Programmatitels, Persons, Geographical Names, other Names, and then the smaller ones from the nongtaa. 
Issue is that harvesting and saving the concepts to file and load it into the triple store is slow. So that should be improved. We could use the solution for saving catalog data (the one with the sitemaps), so that stuff is better manageable.

**Comment by wmelder** [comment]
@wmelder TODO: cut work up in 'manageable' chunks. Maybe automate some SPARQL requests.

**Comment by wmelder** [comment]
![image](https://user-images.githubusercontent.com/1220375/66549803-61a4bb00-eb44-11e9-8977-a966e79d3560.png)
Issue can be closed if we did this for the data that is now in the store (see the uploaded image)

**Comment by wmelder** [comment]
done now for actualiteiten en hollands nieuws for the onderwerpen, geografischenamen en genre...
more catalogs to follow... but first patch the beng-lod-server, so that it doesn't provide all teh clutter (carriers...)
