### ISSUE TITLE
As an LD user, I want the schema URIs of the NISV schema to resolve

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#65]
E.g. entering http://data.rdlabs.beeldengeluid.nl/schema/Person in a browser should return the statements about that concept type in the schema

**Comment by wmelder** [comment]
also needed for using the schema information within the graph

**Comment by wmelder** [comment]
added routes to point to: 
- the HTML representation in the Ontology => same problem with flask propagating the route.
- the RDF data (retrieved from the triple store) => Flask giving problems since the rdflib Resource class conflicts with the flaskx Resource class.

To be solved in the next sprint.

**Comment by wmelder** [comment]
@mwigham 

You can ask for the resource in turtle format and then the response is turtle. Otherwise the response is an HTML page. 

Jaap is asked for review, because locally the static HTML files don't seem to load in my browser...

## testplan 
- checkout the feature branch feature/resolve_schema_uris_#65 and see if it behaves like you would expect. 
- You need to set the accept type in your request to 'text/turtle' to be able to test the turtle representation. 
- resolve the uri from your browser and look at the HTML.

**Comment by jblom** [comment]
@wmelder will review this more properly later, but one thing is that it is not nice (imho) to use a redirect from `http://data.rdlabs.beeldengeluid.nl/schema/Person` to `http://data.rdlabs.beeldengeluid.nl/docs/class-nisvperson.html`. 

The downside is that the calling client needs to be able to follow a redirect, just to get the data. Also: a browser user will see the path change in the address bar because of this.

**Comment by wmelder** [comment]
@jblom I seems to be the best practice for LD to redirect a URI to a representation for that resource. Consider the fact that the URI can actually be referring to something in the real world ('a person from flesh and blood'). Some web server can never give you that in the response, but it can give you a digital representation of facts on that resource. It is even willingly to redirect you to the URL of that page. I checked the how schema.org is doing it: e.g. ```curl -L -v -H "Accept: text/turtle" https://schema.org/Person```. It is partly base on this best practices: https://www.w3.org/2001/sw/BestPractices/VM/http-examples/2006-01-18/ and [here ](https://schema.org/docs/developers.html)i s schema.org for developers information.

**Comment by wmelder** [comment]
I prepared the paths for the docs to check out at /schema/. All resources now also checkout with their URI /schema/<resource_name>. All looks nice now. It does still redirect, but I think that's fine.
Will do a pull request for review.

**Comment by wmelder** [comment]
will merge this now and put it in done
